name: cicd

# Run workflow on push
on: 
  push:
    branches: ['**']  # Run on all branches

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    # Test code quality and functionality across multiple environments
    runs-on: ${{ matrix.os }}
    
    strategy:
      # Don't cancel all jobs if one fails - collect all failures
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.13"]
        os: [ubuntu-latest, macos-latest]  # windows-latest,

    steps:
      # check out repos
      - name: Check out repo
        uses: actions/checkout@v4
      
      # Set up Python environment with specified version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      # Install and setup uv
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "requirements.txt"
      
      # Install dependencies with uv
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install flake8 pytest pytest-cov
          uv pip install -r requirements.txt
          uv pip install -e ".[dev]"
        shell: bash  # ensure consistent shell across all OS
      
      - name: Lint with flake8
        run: |
          source .venv/bin/activate
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        shell: bash
      
      - name: Test with pytest and collect coverage
        run: |
          source .venv/bin/activate
          pytest --cov=timeseries_compute --cov-report=xml --cov-report=term
        shell: bash
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@3440e5ef70c638a9f44602a80ab017feee1309fe
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: garthmortensen/timeseries-compute

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@f2dba722c67b86c6caa034178c6e4d35335f6706
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  docker:
    name: Build and Push Docker Image
    # Create and publish Docker image to DockerHub
    needs: test  # gate this behind successful tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@afeb29a6e0d7d6258844ecabe6eba67d13443680
      
      - name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: goattheprofessionalmeower/timeseries-compute
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@84ad562665bb303b549fec655d1b64f9945f3f91
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build:
    name: Build package
    # Create Python package distribution files
    needs: test  # gate this behind successful tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install uv and build dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          source ~/.cargo/env
          uv venv
          source .venv/bin/activate
          uv pip install build twine
      
      # Build both wheel and source distribution
      - name: Build package
        run: |
          source .venv/bin/activate
          python -m build
      
      # Verify package integrity with twine
      - name: Check package with twine
        run: |
          source .venv/bin/activate
          twine check dist/*
      
      # Upload built package as an artifact
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: distributions
          path: dist/
  
  docs:
    name: Build documentation
    # Generate API documentation from source code
    needs: test   # gate this behind successful tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install uv and dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          source ~/.cargo/env
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          uv pip install -e ".[docs]"
      
      - name: Build documentation
        run: |
          source .venv/bin/activate
          cd docs
          sphinx-build -b html source build
      
      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz
      
      - name: Generate UML diagrams
        run: |
          source .venv/bin/activate
          uv pip install pylint
          mkdir -p images
          pyreverse -o png -d images timeseries_compute
      
      - name: Upload UML diagrams as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uml-diagrams
          path: images/
      
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/html/
  
  publish:
    name: Publish to PyPI
    # Deploy package to Python Package Index
    needs: [test, build, docs]
    runs-on: ubuntu-latest
    
    # add permissions for PyPI trusted publishing
    permissions:
      id-token: write  # required for requesting the JWT (JSON Web Token)
      contents: read   # required for actions/checkout
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Download package distributions
        uses: actions/download-artifact@v4
        with:
          name: distributions
          path: dist/
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          verify-metadata: true
          verbose: true
          skip-existing: false
